### PR TITLE
Fix UG

### LINKED ISSUE #217: [PE-D] Overlapping interval of timestep itinerary
add-itinerary n/ sigma mu delta sd/01-10-2020 ed/01-10-9999
add-itinerary n/ sigma mu delta sd/02-10-2020 ed/01-10-9999

I can have 2 of the same named, that overlap in time range.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: blackonyyx/ped#2

### LINKED ISSUE #218: [PE-D] Timing of event clashes with opening-closing hour
The attraction has been given a opening time of 10-6pm but i can put it in itinerary at 7-8pm

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: blackonyyx/ped#3

### PR DESCRIPTION
**Pull request by Robinho98**
Closes #218 and closes #217

### CODE REVIEW

File: src/main/java/seedu/address/MainApp.java [hunk 1]
```diff
@@ -107,7 +107,7 @@ private Model initModelManager(Storage storage, ReadOnlyUserPrefs userPrefs) {
         try {
             itineraryListOptional = storage.readItineraryList();
             if (itineraryListOptional.isEmpty()) {
-                logger.info("Itinerary data file not found. Will be starting with an empty ItineraryList");
+                logger.info("Itinerary data file not found. Will be starting with an sample ItineraryList");
```
Comment (limkoonkiat) [inline src/main/java/seedu/address/MainApp.java:110]: Should be with "a" instead of "an"

Comment (Robinho98) [reply src/main/java/seedu/address/MainApp.java:110]: ok im changing it in my next pr
